title: 'Story Chat Radio'
default_lang: en
author:
  name: 'Nick Hayward'
  email: nhayward2011@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'This is Story Chat Radio!'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /home
