title: 'Story Chat Radio'
default_lang: en
author:
  name: 'Nick Hayward'
  email: nhayward2011@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'This is Story Chat Radio!'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /home
social_links:
  -
    title: YouTube
    link: https://www.youtube.com/channel/UCVgBO3mHLqhtVZWRn0BmFEA
    image: YouTube.png
  -
    title: Twitter
    link: https://twitter.com/StoryChatRadio
    image: Twitter.png
  -
    title: Instagram
    link: https://www.instagram.com/storychatradio
    image: Instagram.png
